/** @type {import('tailwindcss').Config} */
module.exports = {
  prefix: 'tw-',
  important: true,
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'status-text': '#000000E0',
        line: '#D9D9D9',
        primary: '#FF5629',
        'primary-hover': '#D93B18',
        body: 'rgb(0, 0, 0)',
        'bg-disabled': '#F5F5F5',
        'bg-hover-subtle': '#0000000D',
        'checkbox-disabled-text': '#00000040',
        white: '#FFFFFF',
        'text-disabled': 'rgba(0, 0, 0, 0.38)',
        'text-secondary': 'rgba(0, 0, 0, 0.45)',
        error: '#DC3545',
        info: '#E6F4FF',
        'secondary': '#E5E5E5',
        'secondary-hover': '#D9D9D9',
        'secondary-active': '#CCCCCC',
        'secondary-disabled': '#ECECEC',
        'link-hover': '#E64A1F',
        'link-active': '#CC3A15',
        'border-toggle': 'rgba(0, 0, 0, 0.25)',
        'bg-hover': '#F5F5F5',
        brand: '#ff5628',
        pagination: 'rgba(0, 0, 0, 0.88)',
        'active-pagination': 'rgba(0, 0, 0, 0.05)',
        'pagination-border': 'rgba(0, 0, 0, 0.15)',
        'status-badge-bg': '#D9F7BE',
        'status-badge-text': 'rgba(0, 0, 0, 0.88)',
        'primary-bg-light': '#FF56290D',
        'secondary-custom': '#000000A6',
        'unlinked-muted': '#00000073',
        'status-success-bg': '#D9F7BE',
        'status-warning-bg': '#FFF7E6',
        'status-error-bg': '#FFCCC7',
        'alert-error-bg': '#FFEBEB',
      },
      borderRadius: {
        sm: '2px',
        DEFAULT: '4px',
        input: '4px',
        md: '6px',
        lg: '8px',
        xl: '12px',
        '2xl': '16px',
      },
      fontFamily: {
        sans: ['Roboto', 'sans-serif'],
      },
      fontWeight: {
        normal: '400',
        medium: '500',
      },
      height: {
        'input-default': '32px',
        'input-medium': '36px',
        'input-large': '40px',
        'button-small': '24px',
        'button-default': '32px',
        'button-medium': '36px',
        'button-large': '40px',
        'dropdown-toggle': '32px',
        'dropdown-item': '32px',
      },
      minHeight: {
        'input-default': '32px',
        'input-medium': '36px',
        'input-large': '40px',
        'button-small': '24px',
        'button-default': '32px',
        'button-medium': '36px',
        'button-large': '40px',
        'dropdown-item': '32px',
      },
      maxHeight: {
        'input-default': '32px',
        'input-medium': '36px',
        'input-large': '40px',
      },
      padding: {
        'input-y': '8px',
        'input-x': '12px',
        'addon-x': '12px',
        'button-small': '0 12px',
        'button-default': '0 16px',
        'button-medium': '0 18px',
        'button-large': '0 20px',
        'dropdown-toggle': '0 10px',
        'dropdown-item': '4px',
        'dropdown-menu': '4px',
      },
      zIndex: {
        'input-base': '1',
        'input-overlay': '10',
        'dropdown-menu': '99999',
      },
      spacing: {
        '1.5': '6px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '4.5': '18px',
        '8': '32px',
        '10': '40px',
        '28': '112px',
      },
      right: {
        '45px': '45px',
      },
      top: {
        'label-inside': '20%',
      },
      transitionProperty: {
        'border-color': 'border-color',
      },
      transitionTimingFunction: {
        input: 'ease-in-out',
        button: 'ease-in-out',
        dropdown: 'ease-in-out',
      },
      transitionDuration: {
        input: '200ms',
        button: '200ms',
        dropdown: '200ms',
      },
      boxShadow: {
        'dropdown-menu': '0px 9px 28px 8px rgba(0, 0, 0, 0.15)',
        sm: '0px 1px 2px 0px rgba(0, 0, 0, 0.03)',
        md: '0px 2px 4px 0px rgba(0, 0, 0, 0.02)',
        lg: '0px 1px 6px -1px rgba(0, 0, 0, 0.02)',
      },
      minWidth: {
        'dropdown-menu': '150px',
      },
      gap: {
        'label-icon': '4px',
        'button-icon': '8px',
        'dropdown-chevron': '8px',
      },
      margin: {
        'dropdown-chevron': '8px',
      },
      lineHeight: {
        'dropdown-toggle': '22px',
      },
      fontSize: {
        xs: ['12px', { lineHeight: '16px' }],
        sm: ['13px', { lineHeight: '18px' }],
        base: ['14px', { lineHeight: '22px' }],
        md: ['16px', { lineHeight: '22px' }],
        lg: ['18px', { lineHeight: '24px' }],
        xl: ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
      }
    },
  },
  plugins: [],
}

